Repository RedHatQE/cloud-tools, pull requests merged in 2023-06, with the labels that each got.

#26 Delete AWS resources
  .flake8
  clouds/aws/aws_utils.py
  clouds/aws/delete_s3_velero_bucket.py
  clouds/aws/session_clients.py
  clouds/aws/utilities/delete_aws_resources.py
  pyproject.toml
Labels: verified, Approved-by-myakove, size/XL, branch-main, can-be-merged

#50 Update README.md
  README.md
Labels: Approved-by-myakove, branch-main, size/XS, Approved-by-oharan2

#75 Get aws config file from env
  clouds/aws/aws_utils.py
Labels: verified, Approved-by-myakove, branch-main, size/XS, can-be-merged

#80 Set os env aws credentials and region
  clouds/aws/aws_utils.py
  clouds/aws/utilities/delete_aws_resources.py
Labels: verified, branch-main, Approved-by-rnetser, can-be-merged, size/S

#86 aws cleanup : run in parallel
  .flake8
  clouds/aws/utilities/delete_aws_resources.py
Labels: verified, Approved-by-myakove, branch-main, size/M, needs-rebase
