Repository RedHatQE/cloud-tools, pull requests merged in 2023-03, with the labels that each got.

#1 add aws module
  .github/in-solidarity.yml
  .github/stale.yml
  .pre-commit-config.yaml
  OWNERS
  aws/README.md
  tox.ini
Labels: verified, size/L, Approved-by-myakove

#4 Fix s3 script
  .gitignore
  aws/README.md
  aws/delete_s3_velero_bucket.py
  requirements.txt
Labels: verified, Approved-by-myakove, size/XL, branch-main

#8 Aws creds check
  .flake8
  .gitignore
  .release-it.json
  README.md
  aws/README.md
  clouds/__init__.py
  clouds/aws/README.md
  clouds/aws/__init__.py
  clouds/aws/aws_utils.py
  clouds/aws/delete_s3_velero_bucket.py
  clouds/logger.py
  poetry.lock
  pyproject.toml
  requirements.txt
Labels: verified, Approved-by-myakove, branch-main, size/XXL
