Repository RedHatQE/cloud-tools, pull requests merged in 2023-11, with the labels that each got.

#255 Pre commit use ruff
  .flake8
  .pre-commit-config.yaml
  clouds/aws/aws_utils.py
  clouds/aws/delete_s3_velero_bucket.py
  clouds/aws/roles/roles.py
  clouds/aws/utilities/delete_aws_resources.py
  clouds/gcp/utils.py
  pyproject.toml
Labels: verified, size/L, branch-main, can-be-merged, approved-rnetser

#261 flake8-plugins pin to version
  .pre-commit-config.yaml
Labels: verified, branch-main, size/XS, can-be-merged, approved-rnetser

#285 Update AWS_CREDENTIALS_FILE env var name
  clouds/aws/aws_utils.py
Labels: verified, branch-main, size/XS, can-be-merged, approved-myakove
